### ISSUE TITLE
is there any way to help you?

### ISSUE THREAD

**Issue by Invy55** [DarkWav/SAC-rewrite#2]
Hi, is there any way to help you fnishing the rewrite of this plugin?

**Comment by DarkWav** [comment]
Not really in its current state, but I've been thinking about continuing this.

**Comment by radondev** [comment]
I would be happy to participate in the rewrite. I started LAC in December 2019 but abandoned shortly after due to my lack of motivation, as I discarded the 'SAC-character' and made something entirely new out of it. To prevent such, it would make sense to define some guidelines and a roadmap the rewrite will follow.

After all, I would be happy to help you finish this rewrite.

**Comment by DarkWav** [comment]
Thanks for participating.
So, the following needs to be done:
- A good config file. The old one was kind of messed up.
- A good kick and notify system. The old notify system had serious issues with notifying people it wasn't supposed to.
- A good permissions system.
- The checks need to be ported from the old architecture. (That will be mostly my work I guess)
The noclip check needs a complete rework, so need the combat heuristics, and the Fly check needs cleaning / eventual removal since its kind of useless on top of PMMP's
- Several checks like fastbreak / fastplace / criticals still need to be coded from ground up.

**Comment by radondev** [comment]
Maybe we could switch to a real messenger like discord to coordinate this better.

**Comment by DarkWav** [comment]
I don't know much about discord nor do I have a server, but I do have an account so if you can create something for us go ahead

**Comment by Invy55** [comment]
> Maybe we could switch to a real messenger like discord to coordinate this better.

Yeah, that's a good idea my discord is: Invy55:7131 and my telegram is t.me/asadashinosao

**Comment by Invy55** [comment]
> I don't know much about discord nor do I have a server, but I do have an account so if you can create something for us go ahead

If you want I can create one and give you the link to enter, let me know

**Comment by DarkWav** [comment]
My discord is DarkWav:4845, you and radondev can decide who makes sever

**Comment by Invy55** [comment]
@radondev choose

**Comment by Invy55** [comment]
> My discord is DarkWav:4845, you and radondev can decide who makes sever
I sent you a friend request please accept it

**Comment by radondev** [comment]
Ok, so I setup a server: https://discord.gg/YzX4MVA
